spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR}
      config:
        server-addr: ${NACOS_SERVER_ADDR}

logging:
  level:
    cn.techkg: INFO
